"""Welcome to Reflex! This file outlines the steps to create a basic app."""

import reflex as rx

from rxconfig import config


class State(rx.State):
    """The app state."""
    display: str = ""

    def append(self, value: str):
        self.display += value

    def clear(self):
        self.display = ""

    def calculate(self):
        try:
            self.display = str(eval(self.display))
        except Exception:
            self.display = "yo bro who got you messin up like dat"


def index() -> rx.Component:
    # Welcome Page (Index)
    return rx.container(
        rx.color_mode.button(position="top-right"),
        rx.vstack(
            rx.heading("Calculator.", size="9"),
            spacing="5",
            justify="top",
            min_height="10vh",
        ),
        calcy_index(),
        rx.logo(),
        background_color="#302f38",
        height="100vh",
    )


def calcy_index():
    return rx.container(
        rx.box(State.display,
            text_color="#f4f1eb",
            background_color="#0983c8",
            border_radius="10px",
            width="80%",
            margin="16px",
            padding="16px",
        ),

        rx.flex(
            rx.flex(
                rx.button("1",
                    background="#023e77",
                    padding="2em",
                    border_radius="10px",
                    spacing="1em",
                    align_items="center",
                    justify="center",
                    width="4em",
                    on_click=lambda: State.append("1"),
                ),
                rx.button("2",
                    background="#023e77",
                    padding="2em",
                    border_radius="10px",
                    spacing="1em",
                    align_items="center",
                    justify="center",
                    width="4em",
                    on_click=lambda: State.append("2"),
                ),
                rx.button("3",
                    background="#023e77",
                    padding="2em",
                    border_radius="10px",
                    spacing="1em",
                    align_items="center",
                    width="4em",
                    on_click=lambda: State.append("3"),
                ),
                rx.button("+",
                    background="#badeef",
                    text_color="grey",
                    high_contrast=True,
                    padding="2em",
                    border_radius="10px",
                    spacing="1em",
                    align_items="center",
                    justify="center",
                    width="4em",
                    on_click=lambda: State.append("+"),
                ),
                spacing='2',
                justify="center",
            ),
            rx.flex(
                rx.button("4",
                    background="#023e77",
                    padding="2em",
                    border_radius="10px",
                    spacing="1em",
                    align_items="center",
                    justify="center",
                    width="4em",
                    on_click=lambda: State.append("4"),
                ),
                rx.button("5",
                    background="#023e77",
                    padding="2em",
                    border_radius="10px",
                    spacing="1em",
                    align_items="center",
                    justify="center",
                    width="4em",
                    on_click=lambda: State.append("5"),
                ),
                rx.button("6",
                    background="#023e77",
                    padding="2em",
                    border_radius="10px",
                    spacing="1em",
                    align_items="center",
                    justify="center",
                    width="4em",
                    on_click=lambda: State.append("6"),
                ),
                rx.button("-",
                    background="#badeef",
                    text_color="grey",
                    high_contrast=True,
                    padding="2em",
                    border_radius="10px",
                    spacing="1em",
                    align_items="center",
                    justify="center",
                    width="4em",
                    on_click=lambda: State.append("-"),
                ),
                spacing='2',
                justify="center",
            ),
            rx.flex(
                rx.button("7",
                    background="#023e77",
                    padding="2em",
                    border_radius="10px",
                    spacing="1em",
                    align_items="center",
                    justify="center",
                    width="4em",
                    on_click=lambda: State.append("7"),
                ),
                rx.button("8",
                    background="#023e77",
                    padding="2em",
                    border_radius="10px",
                    spacing="1em",
                    align_items="center",
                    justify="center",
                    width="4em",
                    on_click=lambda: State.append("8"),
                ),
                rx.button("9",
                    background="#023e77",
                    padding="2em",
                    border_radius="10px",
                    spacing="1em",
                    align_items="center",
                    justify="center",
                    width="4em",
                    on_click=lambda: State.append("9"),
                ),
                rx.button("*",
                    background="#badeef",
                    text_color="grey",
                    high_contrast=True,
                    padding="2em",
                    border_radius="10px",
                    spacing="1em",
                    align_items="center",
                    justify="center",
                    width="4em",
                    on_click=lambda: State.append("*"),
                ),
                spacing='2',
                justify="center",
            ),
            rx.flex(
                rx.button("0",
                    background="#023e77",
                    padding="2em",
                    border_radius="10px",
                    spacing="1em",
                    align_items="center",
                    justify="center",
                    width="4em",
                    on_click=lambda: State.append("0"),
                ),
                rx.button(".",
                    background="#badeef",
                    text_color="grey",
                    high_contrast=True,
                    padding="2em",
                    border_radius="10px",
                    spacing="1em",
                    align_items="center",
                    justify="center",
                    width="4em",
                    on_click=lambda: State.append("."),
                ),
                rx.button("/",
                    background="#badeef",
                    text_color="grey",
                    high_contrast=True,
                    padding="2em",
                    border_radius="10px",
                    spacing="1em",
                    align_items="center",
                    justify="center",
                    width="4em",
                    on_click=lambda: State.append("/"),
                ),
                rx.button("=",
                    background="#badeef",
                    text_color="grey",
                    high_contrast=True,
                    padding="2em",
                    border_radius="10px",
                    spacing="1em",
                    align_items="center",
                    justify="center",
                    width="4em",
                    on_click=State.calculate,
                ),
                
                spacing='2',
                justify="center",
            ),
            rx.flex(
                rx.button("AC",
                    background="#eaf0f7",
                    text_color="grey",
                    high_contrast=True,
                    padding="2em",
                    border_radius="10px",
                    spacing="1em",
                    align_items="center",
                    justify="center",
                    width="17.5em",
                    on_click=State.clear,),
                    justify="center",
            ),
            spacing='2',
            direction="column",
            width="80%",
            margin="16px",
            padding="16px",
            justify="center",
        )
    )


app = rx.App()
app.add_page(index)